"""add_soft_delete_and_liveness_columns

Revision ID: 747e6ccc248b
Revises: 
Create Date: 2026-06-05 22:48:54.830280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '747e6ccc248b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('internships', sa.Column('last_seen', sa.DateTime(), nullable=False, server_default=sa.text('NOW()')))
    op.add_column('internships', sa.Column('deactivated_at', sa.DateTime(), nullable=True))
    op.add_column('internships', sa.Column('consecutive_failures', sa.Integer(), nullable=False, server_default=sa.text('0')))
    op.alter_column('internships', 'stipend_numeric',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('internships', 'freshness_score',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('internships', 'description',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=5000),
               existing_nullable=True)
    op.create_index(op.f('ix_internships_confidence'), 'internships', ['confidence'], unique=False)
    op.create_index(op.f('ix_internships_confidence_score'), 'internships', ['confidence_score'], unique=False)
    op.create_index(op.f('ix_internships_confidence_tier'), 'internships', ['confidence_tier'], unique=False)
    op.create_index(op.f('ix_internships_consecutive_failures'), 'internships', ['consecutive_failures'], unique=False)
    op.create_index(op.f('ix_internships_created_at'), 'internships', ['created_at'], unique=False)
    op.create_index(op.f('ix_internships_deactivated_at'), 'internships', ['deactivated_at'], unique=False)
    op.create_index(op.f('ix_internships_freshness_score'), 'internships', ['freshness_score'], unique=False)
    op.create_index(op.f('ix_internships_is_active'), 'internships', ['is_active'], unique=False)
    op.create_index(op.f('ix_internships_last_seen'), 'internships', ['last_seen'], unique=False)
    op.create_index(op.f('ix_internships_legitimacy_score'), 'internships', ['legitimacy_score'], unique=False)
    op.create_index(op.f('ix_internships_paid'), 'internships', ['paid'], unique=False)
    op.create_index(op.f('ix_internships_posted_at'), 'internships', ['posted_at'], unique=False)
    op.create_index(op.f('ix_internships_relevance_score'), 'internships', ['relevance_score'], unique=False)
    op.create_index(op.f('ix_internships_remote'), 'internships', ['remote'], unique=False)
    op.create_index(op.f('ix_internships_source'), 'internships', ['source'], unique=False)
    op.create_index(op.f('ix_internships_stipend_numeric'), 'internships', ['stipend_numeric'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_internships_stipend_numeric'), table_name='internships')
    op.drop_index(op.f('ix_internships_source'), table_name='internships')
    op.drop_index(op.f('ix_internships_remote'), table_name='internships')
    op.drop_index(op.f('ix_internships_relevance_score'), table_name='internships')
    op.drop_index(op.f('ix_internships_posted_at'), table_name='internships')
    op.drop_index(op.f('ix_internships_paid'), table_name='internships')
    op.drop_index(op.f('ix_internships_legitimacy_score'), table_name='internships')
    op.drop_index(op.f('ix_internships_last_seen'), table_name='internships')
    op.drop_index(op.f('ix_internships_is_active'), table_name='internships')
    op.drop_index(op.f('ix_internships_freshness_score'), table_name='internships')
    op.drop_index(op.f('ix_internships_deactivated_at'), table_name='internships')
    op.drop_index(op.f('ix_internships_created_at'), table_name='internships')
    op.drop_index(op.f('ix_internships_consecutive_failures'), table_name='internships')
    op.drop_index(op.f('ix_internships_confidence_tier'), table_name='internships')
    op.drop_index(op.f('ix_internships_confidence_score'), table_name='internships')
    op.drop_index(op.f('ix_internships_confidence'), table_name='internships')
    op.alter_column('internships', 'description',
               existing_type=sa.String(length=5000),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('internships', 'freshness_score',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('internships', 'stipend_numeric',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_column('internships', 'consecutive_failures')
    op.drop_column('internships', 'deactivated_at')
    op.drop_column('internships', 'last_seen')
    # ### end Alembic commands ###
